language: go
go:
  - 1.13.x
env:
  - GO111MODULE=on
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
script:
  - go test -v -covermode=count -coverprofile=coverage_filesystem.out -tags="unit" ./filesystem/...
  - go test -v -covermode=count -coverprofile=coverage_server.out -tags="unit" ./server/...
  - cat coverage_filesystem.out > coverage.out
  - cat coverage_server.out >> coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
